#!/bin/csh
#run the pipeline with arguments specified
#HISTORY
# 101006 GIL complete execution of pipeline 
# 100929 GIL try all w51 data on gbtpipeline
# 100829 GIL try to run on Adam Ginzbergs data
# 100325 GIL revised for existing SDFITS file


set gbtpipeline=/home/sandboxes/gbt_pipeline/gbt_pipeline
if (! -f "imNH3-11.py") then
  cp /users/glangsto/pipelineAlpha/imNH3-11.py .
endif


set you=`whoami`

#Use AIPS with a public number
setenv NUMBERSTR `/users/glangsto/pipelineAlpha/aipsNumber $you`
#Due to strange prompt issues, strip out last 5 digits only
setenv AIPSNUMBER `echo $NUMBERSTR | awk '{print substr($0,length($0)-4,length($0))}'`
echo '--------------------------------------------------'
echo ' Your ('$you') pipeline AIPS number: '$AIPSNUMBER
echo '--------------------------------------------------'

#select NH3 (1,1) scans for this map
$gbtpipeline -i /home/sdfits/TKFPA_29/TKFPA_29.raw.acs.fits -b 14 -e 24 \
    --refscan1=13 --refscan2=26 --units='Tmb' -v 1 \
    --nodisplay


set doImage=/home/sandboxes/gbt_pipeline/doImage

#Now produce the cube and NH3 (1,1) transition line image
$doImage imNH3-11.py $AIPSNUMBER *.sdf

#Next look at line output
casaviewer *NH3-11.fits &

if (! -f "accumNH3-22.py") then
  cp /users/glangsto/pipelineAlpha/accumNH3-22.py .
endif

#Next sum the NH3 (2,2) transition and clean up
$doImage accumNH3-22.py $AIPSNUMBER *.sdf

#Compare the (2,2) transition
casaviewer *NH3-22.fits &
