#!/bin/csh
#run the pipeline with arguments specified
#HISTORY
# 110209 GIL use dbcon.py and mapDefault.py
# 110206 GIL revise for new pipeline arguments
# 101020 GIL produce a temperature map
# 101013 GIL change default location of python code
# 101006 GIL complete execution of pipeline 
# 100929 GIL try all w51 data on gbtpipeline
# 100325 GIL revised for existing SDFITS file

setenv pipehome /home/gbtpipeline/release
set you=`whoami`

#Use AIPS with a public number
#Due to strange prompt issues, strip out last 5 digits only
setenv AIPSNUM `id -u | awk '{print substr($0,length($0)-4,length($0))}'`
echo '--------------------------------------------------'
echo ' Your ('$you') pipeline AIPS number: '$AIPSNUM
echo '--------------------------------------------------'

#select NH3 (1,1) scans for this map
$pipehome/gbtpipeline -i /home/sdfits/TKFPA_29/TKFPA_29.raw.acs.fits -m 14:24 \
    --refscan1=13 --refscan2=26 --units=Tmb -v 4 \
    --imaging-off -n 4.0 --clobber
# --allmaps


########################## Set your data merge script name here
set merge=dbcon.py

#Transfer the python/ParselTongue scripts to local
if (! -f "$merge") then
  cp $pipehome/contrib/$merge .
endif

set doImage=$pipehome/tools/doImage
#Merge all data into a single trimed data set
$doImage $merge $AIPSNUM *.sdf

########################## Set your data mapping script name here
set image=mapDefault.py

#Transfer the python/ParselTongue scripts to local
if (! -f "$image") then
  cp $pipehome/contrib/$image .
endif

#Produce the cube, continuum and baselined images (average 3 channels)
$doImage $image $AIPSNUM 3

#Sum channels to compute Line integration
if (! -f "sumLine.py") then
  cp $pipehome/contrib/sumLine.py .
endif

#Sum line channels for W51 NH3 (1,1)
#v=60 km/sec, line FULL width 20 km/sec
$doImage sumLine.py $AIPSNUM W51-NH3-11 23694.506 60. 20.
casaviewer *NH3-11.fits &     #Look at NH3 (1,1) line output

#Next sum the NH3 (2,2) transition 
$doImage sumLine.py $AIPSNUM W51-NH3-22 23722.6336 60. 20.
casaviewer *NH3-22.fits &     #Compare NH3 (2,2)

#Sum channels to compute Line integration
if (! -f "tempNH3_1122.py") then
  cp $pipehome/contrib/tempNH3_1122.py .
endif

#Produce a temperature map for source Velocity 60 km/sec, width 20 km/sec 
$doImage tempNH3_1122.py $AIPSNUM W51 60. 10. .2
casaviewer W51*T_11_22.fits &     #Examine the temperature map


