#!/bin/bash

if [[ "$PATH" != */home/sandboxes/gbt_mapping_pipeline* ]]
then
    PATH=/home/sandboxes/gbt_mapping_pipeline:"$PATH"
    PATH=/home/sandboxes/jmasters/local/bin:"$PATH"
fi

if [ -z "$PYTHONPATH" ]
then
    PYTHONPATH=/home/sandboxes/gbt_mapping_pipeline
else
    lclpythonpath="$PYTHONPATH"
    if [[ $lclpythonpath != */home/sandboxes/gbt_mapping_pipeline* ]]
    then
        PYTHONPATH=/home/sandboxes/gbt_mapping_pipeline:"$PYTHONPATH"
    fi
fi

export PATH
export PYTHONPATH

echo gbt_mapping_pipeline $*

gbt_mapping_pipeline.py $*
