#!/bin/bash

# This script sets up the  IDL_PATH and IDL_STARTUP for gbtidl
# It then invokes idl via this path - be sure and edit this to
# reflect your local IDL installation.
LOCAL_IDL=/opt/local/bin/idl

# set the below env variable to the location of this installation 
export GBT_IDL_DIR=/home/gbtidl/2.6/gbtidl

# Construct the IDL path.
# IDL always searches "." first, no need to add it in here.
# the leading + means everything from there on down is included.
# <IDL_DEFAULT> is expanded to what it would have been if IDL_PATH wasn't
# set here.  That gets the default IDL code in the installation.
# Contrib is included in the last location.
# An invidual may have a local library at $HOME/gbtidlpro.  That is 
# at the head of the path - so it is search immediately after ".".
export IDL_PATH="/home/sandboxes/kfpa_pipeline:+$HOME/gbtidlpro:$GBT_IDL_DIR:$GBT_IDL_DIR/pro:+$GBT_IDL_DIR/pro:$GBT_IDL_DIR/tests:+$GBT_IDL_DIR/lib:<IDL_DEFAULT>:+$GBT_IDL_DIR/contrib"

# Specify the file with which to begin execution.
export IDL_STARTUP=$GBT_IDL_DIR/STARTUP.IDL

# This section is necessary in Green Bank to set the
# environment variable where the online data is found
if [ -z "$YGOR_TELESCOPE" ]
then
  if [ -a /home/gbt/gbt.bash ]
  then
    source /home/gbt/gbt.bash
  fi
fi

# If an initialization script does not exist in the user's home dir,
# then create one.

if [ ! -e ~/.gbtidl ] 
then 
  echo 'Creating a .gbtidl file in your home directory.'
  echo '; GBTIDL initialization script' > ~/.gbtidl
fi

# Start up IDL and execute STARTUP.IDL (either "idl" or "idlde" will work).
# Should we test that there is an idl somewhere in the path?
if [ -z "$1" ]
then
   exec $LOCAL_IDL
else
   exec $LOCAL_IDL "$@"
fi
