#!/bin/bash

# This is a simple script for reading kfpa pipeline input parameters
# and passing control to idl.
#
# Author: Joe Masters (jmasters@nrao.edu)

# set default parameter values
INFILE=0
BEGINSCAN=0
ENDSCAN=0
VSOURCE=0
VSOURCEWIDTH=0
VSOURCEBEGIN=0
VSOURCEEND=0
REFSCAN1=-1
REFSCAN2=-1
ALLSCANREF=0
SDFITSDIR=0
VERBOSE=0

# check parameters
for i in $*
do
	case $i in
    	--default)
		DEFAULT=YES
		;;
	--infile*)
		INFILE=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--begin-scan*)
		BEGINSCAN=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--end-scan*)
		ENDSCAN=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--vsource-center*)
		VSOURCE=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--vsource-width*)
		VSOURCEWIDTH=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--vsource-begin*)
		VSOURCEBEGIN=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--vsource-end*)
		VSOURCEEND=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--refscan1*)
		REFSCAN1=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--refscan2*)
		REFSCAN2=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--all-scans-as-ref*)
		ALLSCANREF=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--verbose*)
		VERBOSE=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
	--help)
		HELP=HELP
		;;
	-h)
		HELP=HELP
		;;
	--sdfits-dir)
		SDFITSDIR=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
		;;
    *)
        echo "Error:" $i "not recognized"
        ERROR=1
		;;
  	esac
done

if [ ${ERROR} ]; then exit; fi

if [ $# == 0 ] || [[ -n "${HELP}" ]]; then
   echo "Usage: kfpa_pipeline [--infile=filename] [--begin-scan=scan]"
   echo "                     [--end-scan=scan] [--vsource]"
   echo "                     [--vsource-width] [--vsource-begin]"
   echo "                     [--vsource-end] [--refscan1] [--refscan2]"
   echo "                     [--help] [--run-sdfits] [--sdfits-dir=directory]"
   echo "                     [--all-scans-as-ref]"
   echo "Options:"
   echo "  --infile=file           SDFITS file name containing map scans"
   echo "  --begin-scan=scan       beginning map scan number"
   echo "  --end-scan=scan         ending map scan number"
   echo "  --vsource               defines center channel to select (km/sec)"
   echo "  --vsource-width         defines median filter width (km/sec)"
   echo "  --vsource-begin         defines begin channel to select (km/sec)"
   echo "  --vsource-end           defines end channel to select (km/sec)"
   echo "  --sdfits-dir=directory  SDFITS input directory; used if infile"
   echo "                          option is not usable"
   echo "  --refscan1=scan         first reference scan"
   echo "  --refscan2=scan         second reference scan"
   echo "  --all-scans-as-ref=1    use all scans as reference?"
   echo "  --verbose=level         set the verbosity level"
   echo "  -h --help               print this help"
else
   ./gbtidl -quiet -e @createMap.pro -args ${INFILE} ${BEGINSCAN} ${ENDSCAN} \
   ${VSOURCE} ${VSOURCEWIDTH} ${VSOURCEBEGIN} ${VSOURCEEND} ${SDFITSDIR} \
   ${REFSCAN1} ${REFSCAN2} ${ALLSCANREF} ${VERBOSE}
fi
