#!/bin/bash

me=`basename $0`

if [ $me = "gbtpipeline" ]; then

	if [[ "$PATH" != */home/gbtpipeline/release* ]]
	then
		PATH=/home/gbt7/norman/bin:"$PATH"
		PATH=/home/gbtpipeline/release/tools:"$PATH"
		PATH=/home/gbtpipeline/release:"$PATH"
	fi
	
	if [ -z "$PYTHONPATH" ]
	then
		PYTHONPATH=/home/gbtpipeline/release/contrib
		PYTHONPATH=/home/gbtpipeline/release:"$PYTHONPATH"
	else
		lclpythonpath="$PYTHONPATH"
		if [[ $lclpythonpath != */home/gbtpipeline/release* ]]
		then
			PYTHONPATH=/home/gbtpipeline/release/contrib:"$PYTHONPATH"
			PYTHONPATH=/home/gbtpipeline/release:"$PYTHONPATH"
		fi
	fi

elif [ $me = "gbtpipeline-test" ]; then
	echo "test" $me

	if [[ "$PATH" != */home/gbtpipeline/integration* ]]
	then
		PATH=/home/gbt7/norman/bin:"$PATH"
		PATH=/home/gbtpipeline/integration/tools:"$PATH"
		PATH=/home/gbtpipeline/integration:"$PATH"
	fi
	
	if [ -z "$PYTHONPATH" ]
	then
		PYTHONPATH=/home/gbtpipeline/integration/contrib
		PYTHONPATH=/home/gbtpipeline/integration:"$PYTHONPATH"
	else
		lclpythonpath="$PYTHONPATH"
		if [[ $lclpythonpath != */home/gbtpipeline/integration* ]]
		then
			PYTHONPATH=/home/gbtpipeline/integration/contrib:"$PYTHONPATH"
			PYTHONPATH=/home/gbtpipeline/integration:"$PYTHONPATH"
		fi
	fi

else
	echo "unknown" $me
fi

export PATH
export PYTHONPATH

echo $me $*

gbt_pipeline.py $*
