#!/bin/bash


# --------------- check the machine architecture and OS version before running
ARCH=`arch`
retval=0
if [ $ARCH != 'x86_64' ]; then
    echo -n "The machine arctitecture must be 64-bit.  "
    echo    "Please find another machine and continue."
    retval=1
fi
 
ret=`grep 'release 6.' /etc/redhat-release`
if [ $? -ne 0 ]
then
    echo -n "The operating system must be Redhat Version 6.  "
    echo    "Please find another machine and continue."
    retval=2
fi
if [ $retval -ne 0 ]
then
    exit $retval 
fi

# --------- get the path of the script pipeline script to determine the version

fullpath=`readlink -f $0`
me=`dirname $fullpath`

if [ $me = "/home/gbtpipeline/integration" ]; then
	echo "!!!!!!!!!! TEST VERSION !!!!!!!!!!!!"
        VERSION='integration'

elif [ $me = "/home/gbtpipeline/release" ]; then
        VERSION='release'

elif [ $me = "/home/gbtpipeline/old" ]; then
        VERSION='old'
else
    # assume integration, actual path of script is probably a personal sandbox
        echo "!!!! UNKNOWN VERSION, ASSUMING TEST ENVIRONMENT !!!!"
        VERSION='integration'        
fi

# if the pipeline tools directory is not included in the PATH, add it
if [[ "$PATH" != *${me}* ]]
then
        PATH=${me}/tools:"$PATH"
fi

# set the PYTHONPATH, or add to it
if [ -z "$PYTHONPATH" ]
then
        PYTHONPATH=${me}/contrib
        PYTHONPATH=${me}:"$PYTHONPATH"
else
        lclpythonpath="$PYTHONPATH"
        if [[ $lclpythonpath != *${me}* ]]
        then
                PYTHONPATH=${me}/contrib:"$PYTHONPATH"
                PYTHONPATH=${me}:"$PYTHONPATH"
        fi
fi

export PATH
export PYTHONPATH

if [ $# -gt 0 ]; then
    echo "gbtpipeline" $*
fi

source /home/gbt7/pipeline/${VERSION}-env/bin/activate
export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH

STAT_FILE="/home/scratch/pipeline/stats.log"
if [ -w $STAT_FILE ]; then
    echo `whoami`,`date`,${VERSION},$* >> $STAT_FILE
fi

python ${me}/gbt_pipeline.py $*

