#!/bin/bash

echo $0  # identify this script in log files

INSTALL_DIR=/home/gbt7/pipeline

# activate virtualenv
source ${INSTALL_DIR}/imaging-env/bin/activate

# initialize AIPS
AIPS_ROOT=/home/aips
. $AIPS_ROOT/LOGIN.SH

# $CDOLD # use OLD version
$CDNEW # use NEW version
# $CDTST # use TST version

PYTHONPATH=${INSTALL_DIR}/obit/Obit/python/ LD_LIBRARY_PATH=/opt/local/lib:${INSTALL_DIR}/obit/Obit ${INSTALL_DIR}/bin/ParselTongue  $*

deactivate
