#!/bin/bash

echo $0  # identify this script in log files

INSTALL_DIR=/home/gbt7/pipeline

# initialize AIPS
AIPS_ROOT=/home/aips
. $AIPS_ROOT/LOGIN.SH

# $CDOLD # use OLD version
# $CDNEW # use NEW version
# $CDTST # use TST version

$INSTALL_DIR/bin/ParselTongue $*
